name: Checks

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  python-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14.3"
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Lint with ruff
        working-directory: backend
        run: ruff check .
