name: Daily Report

on:
  # schedule:
  #   - cron: "0 2 * * *"

  workflow_dispatch:

jobs:
  send-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14.3"
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Send daily reports
        working-directory: backend
        run: python send_daily_reports.python
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY}}
          ADZUNA_APP_ID: ${{ secrets.ADZUNA_APP_ID }}
          ADZUNA_API_KEY: ${{ secrets.ADZUNA_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY}}